### ISSUE TITLE
How do I actually get the mod?

### ISSUE THREAD

**Issue by CommandCracker8** [8s2/IllegalBlocks#1]
All in the title

**Comment by GoofinJaxOG** [comment]
yes how?
i literally cant
it just closes minecraft

**Comment by GoofinJaxOG** [comment]
> yes how? i literally cant it just closes minecraft

i know the reason (its not a jar file) but i dont know how to fix it

**Comment by emortaldev** [comment]
You would have to download the source and compile it. I have compiled it in a fork so you can download it quicker https://github.com/emortaldev/IllegalBlocks/releases/tag/1.0.0

**Comment by CommandCracker8** [comment]
Thanks! It's funny I actually remembered how to do that last night so I already had a jar but thanks anyway :)
